#pragma once

enum class Obj {
	NONE,
	STATIC_BOX, MOVABLE_BOX, PORTAL_BOX,
	PLAYER, PLAYER_BULLET,
	ENEMY, ENEMY_BULLET
};

enum class Tex {
	TEST, BACK_GROUND, FRONT_FRAME,
	BLOCKBOX_ROCK, PORTALBOX_DOOR,
	P_BLOOD1, P_BLOOD2, P_BLOOD3,
	PLAYER_HEAD, PLAYER_BODY,
	PLAYER_BULLET, ENEMY_BULLET,
	ENEMY_MOMS_HAND, ENEMY_TENTACLE, ENEMY_POLYC
};