#pragma once

enum class OBJ {
	NONE,
	BLOCK_BOX, PORTAL_BOX, OBJ_BOX,
	PLAYER, PLAYER_BULLET,
	GROUND_ENEMY, SKY_ENEMY, ENEMY_BULLET
};

enum class TEX {
	TEST, SCENE_TITLE, SCENE_ENDING,
	BACK_GROUND, FRONT_FRAME, FRONT_HPBAR_FRAME,
	PORTALBOX_DOOR, OBJBOX_ROCK,
	P_BLOOD1, P_BLOOD2, P_BLOOD3, P_BLOOD4, P_BLOOD5, P_BLOOD6,
	P_EXPLOSION1, P_EXPLOSION2, P_EXPLOSION3,
	PLAYER_HEAD, PLAYER_BODY,
	PLAYER_BULLET, ENEMY_BULLET,
	ENEMY_MOMS_HAND, ENEMY_TENTACLE, ENEMY_POLYC, ENEMY_FLY, ENEMY_JUDAS
};