#pragma once

enum class Obj {
	NONE,
	BLOCK_BOX, PORTAL_BOX, OBJ_BOX,
	PLAYER, PLAYER_BULLET,
	ENEMY, ENEMY_BULLET
};

enum class Tex {
	TEST, BACK_GROUND, FRONT_FRAME,
	PORTALBOX_DOOR, OBJBOX_ROCK,
	P_BLOOD1, P_BLOOD2, P_BLOOD3, P_BLOOD4, P_BLOOD5,
	P_EXPLOSION1, P_EXPLOSION2,
	PLAYER_HEAD, PLAYER_BODY,
	PLAYER_BULLET, ENEMY_BULLET,
	ENEMY_MOMS_HAND, ENEMY_TENTACLE, ENEMY_POLYC, ENEMY_FLY
};